function parameters = parameters()
	parameters.inFileOrOp= 'TimeSerie_G7.mat';
	parameters.txFun= 'exponential';
	parameters.lrnRate= 0.8;
	parameters.populationSize= 300;
	parameters.generations= 15;
	parameters.G= 0.8; %Porcentaje de problacion a reemplazar
	parameters.replaceMethod= 'rep2'; % rep1 | rep2 | rep3
	parameters.selCriteria= 'Ruleta'; %    Mix | Elite | Boltzman | Ruleta | Torneos | Universal
	parameters.repCriteria=	'Ruleta'; % Mix | Elite | Boltzman | Ruleta | Torneos | Universal
	parameters.crossover= 'Unif'; % 2Points | Anular | Classic | Unif
	parameters.pcross= 0.7;
	parameters.mutation= 'Classic2'; %Classic1 | Classic2
	parameters.pmut=0.005;
	parameters.mutAdaptation= 1;
	parameters.pbackprop= 0.00;
	parameters.selMixCriteria= 'Universal';
	parameters.selMixN= 4;
	parameters.minError = 0.005;
	parameters.breakMethod = 'Optimo';
endfunction